name: api_request_helper_flutter
description: Api Request Helper Flutter is a repository that handles http calls
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  exceptions_flutter:
    git:
      url: "https://github.com/ezraaaa/exceptions_flutter.git"
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
