name: weather_provider
description: Data Provider which manages weather raw data
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  api_request_helper_flutter:
    path: ../../api_request_helper_flutter
  equatable: ^2.0.5
  exceptions_flutter:
    git:
      url: "https://github.com/ezraaaa/exceptions_flutter.git"
  flutter:
    sdk: flutter
  http: ^1.2.1
  json_annotation: ^4.9.0
  uri: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
