name: flutther
description: Flutther is a weather app made of Flutter with OpenWeatherMap and flutter_bloc
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  breakpoint: ^1.2.0
  common_widgets_flutter:
    path: packages/common_widgets_flutter
  equatable: ^2.0.5
  firebase_analytics: ^10.10.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_remote_config: ^4.4.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.18.1
  location: ^6.0.2
  material_design_icons_flutter: ^7.0.7296
  weather_provider:
    path: packages/weather/weather_provider
  weather_repository:
    path: packages/weather/weather_repository

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
