name: flutther
description: Flutther is a weather app made of Flutter with OpenWeatherMap and flutter_bloc
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  breakpoint: ^1.2.0
  common_widgets_flutter:
    path: packages/common_widgets_flutter
  equatable: ^2.0.5
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_remote_config: ^5.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  permission_handler: ^11.3.1
  weather_provider:
    path: packages/weather/weather_provider
  weather_repository:
    path: packages/weather/weather_repository

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
