// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD36JIw0NecB04WWp8NWqHh2G8LAAaCLPY',
    appId: '1:49277361868:web:c7c9339bd925d5fb99ec69',
    messagingSenderId: '49277361868',
    projectId: 'flutther-prod',
    authDomain: 'flutther-prod.firebaseapp.com',
    storageBucket: 'flutther-prod.appspot.com',
    measurementId: 'G-31SWG24P8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO2NDI4DJEEiy6s0vqYhwNLg0qTzuiRV8',
    appId: '1:49277361868:android:dda86b2fd66f45ff99ec69',
    messagingSenderId: '49277361868',
    projectId: 'flutther-prod',
    storageBucket: 'flutther-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAckPJEPxh_b5xzGK6mW9_A-A5IDTHhzKo',
    appId: '1:49277361868:ios:e7e0e9635be5fbed99ec69',
    messagingSenderId: '49277361868',
    projectId: 'flutther-prod',
    storageBucket: 'flutther-prod.appspot.com',
    iosBundleId: 'xyz.ezragunn.flutther',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAckPJEPxh_b5xzGK6mW9_A-A5IDTHhzKo',
    appId: '1:49277361868:ios:e7e0e9635be5fbed99ec69',
    messagingSenderId: '49277361868',
    projectId: 'flutther-prod',
    storageBucket: 'flutther-prod.appspot.com',
    iosBundleId: 'xyz.ezragunn.flutther',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD36JIw0NecB04WWp8NWqHh2G8LAAaCLPY',
    appId: '1:49277361868:web:595bbe5ed2c53e5499ec69',
    messagingSenderId: '49277361868',
    projectId: 'flutther-prod',
    authDomain: 'flutther-prod.firebaseapp.com',
    storageBucket: 'flutther-prod.appspot.com',
    measurementId: 'G-2FNMSLB2JL',
  );

}