// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkByh_a_KQFKPwe0w_4dssNnLPZuCKLXw',
    appId: '1:856949054825:web:9e84e2c6799fc800b231f8',
    messagingSenderId: '856949054825',
    projectId: 'flutther-dev',
    authDomain: 'flutther-dev.firebaseapp.com',
    storageBucket: 'flutther-dev.appspot.com',
    measurementId: 'G-FNYBDZ0PV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvGAVI0aG8XgfJGouSCbl_RQsC7qSHOBI',
    appId: '1:856949054825:android:1ae67c1e3bb1fcbfb231f8',
    messagingSenderId: '856949054825',
    projectId: 'flutther-dev',
    storageBucket: 'flutther-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBQZ9dADOrhjR_hf3yJ6kNx8N9wGHBqTA',
    appId: '1:856949054825:ios:2950b217e554f5b7b231f8',
    messagingSenderId: '856949054825',
    projectId: 'flutther-dev',
    storageBucket: 'flutther-dev.appspot.com',
    iosBundleId: 'xyz.ezragunn.flutther-dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBQZ9dADOrhjR_hf3yJ6kNx8N9wGHBqTA',
    appId: '1:856949054825:ios:2950b217e554f5b7b231f8',
    messagingSenderId: '856949054825',
    projectId: 'flutther-dev',
    storageBucket: 'flutther-dev.appspot.com',
    iosBundleId: 'xyz.ezragunn.flutther-dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkByh_a_KQFKPwe0w_4dssNnLPZuCKLXw',
    appId: '1:856949054825:web:853dba9a212a36beb231f8',
    messagingSenderId: '856949054825',
    projectId: 'flutther-dev',
    authDomain: 'flutther-dev.firebaseapp.com',
    storageBucket: 'flutther-dev.appspot.com',
    measurementId: 'G-TZ7ZXB049Q',
  );

}